Neural Network with one input and one output

In [1]:
# The network:

weight = 0.2 
def my_neural_network(input, weight):
    prediction = input * weight
    return prediction


In [4]:
# How we use the network to predict something:

number_of_years = [8.5, 9.5, 10, 9]
input = number_of_years[0]
pred = my_neural_network(input,weight)
print(pred)

1.7000000000000002


Neural network accepts an input variable as information and a weight variable as knowledge and outputs a prediction.It uses the knowledge in the weights to interpret the information in the input data.
Another way to think about a neural network’s weight value is as a measure of sensitivity 
between the input of the network and its prediction. If the weight is very high, then even the 
tiniest input can create a really large prediction! If the weight is very small, then even large 
inputs will make small predictions.

## Making a Prediction with Multiple Inputs
used in prediction

In [16]:
def cal_weightedsum(a,b):# weighted sum also called dot product
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

In [17]:
weights = [0.1, 0.2, 0] 
    
def my_neural_network(input, weights):
    pred = cal_weightedsum(input,weights)
    return pred


In [18]:
eng =  [8.5, 9.5, 9.9, 9.0]
hindi = [0.65, 0.8, 0.8, 0.9]
maths = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [eng[0],hindi[0],maths[0]]
pred = my_neural_network(input,weights)
print(pred)

0.9800000000000001


## with numpy
no need of cal_weightedsum function

In [20]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def my_neural_network(input, weights):
    pred = input.dot(weights)# substitute of cal_weightedsum function
    return pred
    
eng =  np.array([8.5, 9.5, 9.9, 9.0])
hindi = np.array([0.65, 0.8, 0.8, 0.9])
maths = np.array([1.2, 1.3, 0.5, 1.0])

# Input corresponds to every entry
# for the first game of the season.

input = np.array([eng[0],hindi[0],maths[0]])
pred = my_neural_network(input,weights)

print(pred)

0.9800000000000001


## Making a Prediction with Multiple Outputs
used in classification

In [22]:
def ele_mul(number,vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [0.3, 0.2, 0.9] 

def my_neural_network(input, weights):
    pred = ele_mul(input,weights)
    return pred
    
marks = [0.65, 0.8, 0.8, 0.9]
input = marks[0]
pred = my_neural_network(input,weights)

print(pred)

[0.195, 0.13, 0.5850000000000001]


## Predicting with Multiple Inputs & Outputs
mostly used in image and nlp

a weight connects each 
input node to each output node, and prediction occurs in the usual way.

In [24]:
# weights are taken as column vector, 
# where each row contains number of weights equal to number of inputs and vector length equal to number of outputs


weights = [ [0.1, 0.1, -0.3], #pass
            [0.1, 0.2, 0.0], # fail
            [0.0, 1.3, 0.1] ] # compartment

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred



eng =  [8.5, 9.5, 9.9, 9.0]
hindi = [0.65,0.8, 0.8, 0.9]
maths = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [eng[0],hindi[0],maths[0]]
pred = neural_network(input,weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


## Predicting on Predictions

introducing hidden layer between input and output layer

In [26]:
#toes %win #fans
ih_wgt = [ [0.1, 0.2, -0.1], #hidden layer first neuron [0]
           [-0.1,0.1, 0.9], #hidden layer second neuron[1]
           [0.1, 0.4, 0.1] ] #hidden layer third neuron[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1, -0.3], #pass 
           [0.1, 0.2, 0.0], # fail
           [0.0, 1.3, 0.1] ] #compartment

weights = [ih_wgt, hp_wgt]

def my_neural_network(input, weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred

eng =  [8.5, 9.5, 9.9, 9.0]
hindi = [0.65,0.8, 0.8, 0.9]
maths = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [eng[0],hindi[0],maths[0]]
pred = my_neural_network(input,weights)

print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [31]:
# numpy version of above code
import numpy as np

ih_wgt = np.array([ 
            [0.1, 0.2, -0.1], #hidden layer first neuron [0]
            [-0.1,0.1, 0.9], #hidden layer second neuron[1]
            [0.1, 0.4, 0.1]]).T #hidden layer third neuron[2]


           #hid[0] hid[1] hid[2]
hp_wgt = np.array( [ [0.3, 1.1, -0.3], #pass 
           [0.1, 0.2, 0.0], # fail
           [0.0, 1.3, 0.1] ]).T #compartment

weights = [ih_wgt, hp_wgt]

def my_neural_network(input, weights):

    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


eng =  np.array([8.5, 9.5, 9.9, 9.0])
hindi = np.array([0.65,0.8, 0.8, 0.9])
maths = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([eng[0],hindi[0],maths[0]])

pred = my_neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


## learning numpy for deep learning

In [32]:
import numpy as np

a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3], # a matrix
              [4,5,6,7]])

d = np.zeros((2,4)) # (2x4 matrix of zeros)
e = np.random.rand(2,5) # random 2x5
# matrix with all numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.00874875 0.29014907 0.10504218 0.24350188 0.6741979 ]
 [0.12125314 0.56265012 0.81307577 0.81915729 0.75874036]]


In [33]:
print(a * 0.1) # multiplies every number in vector "a" by 0.1
      
print(c * 0.2) # multiplies every number in matrix "c" by 0.2
      
print(a * b) # multiplies elementwise between a and b (columns paired up)
      
print(a * b * 0.2) # elementwise multiplication then multiplied by 0.2
      
print(a * c) # since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"

print(a * e) # since a and e don't have the same number of columns, this
# throws a "Value Error: operands could not be broadcast together with.."

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [34]:
a = np.zeros((1,4)) # vector of length 4
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape)

(1, 3)


In [35]:
a = np.zeros((2,4)) # matrix with 2 rows and 4 columns
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape) # outputs (2,3)

e = np.zeros((2,1)) # matrix with 2 rows and 1 columns
f = np.zeros((1,3)) # matrix with 1 row & 3 columns

g = e.dot(f)
print(g.shape) # outputs (2,3)

h = np.zeros((5,4)).T # matrix with 4 rows and 5 columns
i = np.zeros((5,6)) # matrix with 6 rows & 5 columns

j = h.dot(i)
print(j.shape) # outputs (4,6)

h = np.zeros((5,4)) # matrix with 5 rows and 4 columns
i = np.zeros((5,6)) # matrix with 5 rows & 6 columns
j = h.dot(i)
print(j.shape) # throws an error

(2, 3)
(2, 3)
(4, 6)


ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)